### ISSUE TITLE
Use environment variable to specify the directory to interact with.

### ISSUE THREAD

**Issue by brandoncc** [stormpath/stormpath-rails#28]
I need to have a directory for each environment (as StormPath suggests) but the gem doesn't support it currently.

**Comment by DamirSvrtan** [comment]
Hey @brandoncc - we have release a new version of the gem. As this is pretty much a custom request, I'd say it needs custom development. 

We are now offering a way to override controllers: https://github.com/stormpath/stormpath-rails#overriding-stormpath

That seems like a pretty good place to kickstart your custom needs. What do you think about that?  (ofcourse if you're still interested as it's almost been two years since you left the comment).

cc @omgitstom
