### ISSUE TITLE
Rails Multitenancy

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-rails#68]
https://github.com/stormpath/stormpath-framework-spec/blob/master/multi-tenancy.md

**Comment by cilim** [comment]
1. -opt-in configuration - _the MT configuration to be added_-
2. -multitenancy configuration verification - _class that makes sure the MT configuration is set correctly_-
3. -login with organization-
4. registration with organization
5. -Default organization resolver - receives http request for inspection-
6. Default organization resolver - return organization that is mapped to the current application
7. Default organization resolver - check the request host first, then the body for `organizationNameKey` if host is empty
8. -Default organization resolver - act as standalone class-
9. Providing custom resolver instead of using the default one
10. Attach organization to the authentication requests (-login-, register)
11. If subdomain doesnt resolve org, redirect user to `parent_domain/view` to provide org context. If bad, error, if good, redirect back to the view but on the correct subdomain.

**Comment by cilim** [comment]
How is the stormpath.yml configuration file going to be extended concerning the labels and placeholders for the organization select form?

For example:
```
organizationSelect:
  form:
    fields:
      organizationNameKey:
        label: Enter your organization name key
        placeholder: e.g. my company
```

Same question for the custom organization resolver:

```
customOrganizationResolver:
  enabled: false
  path: 'app/services/organization_resolver'
```
